before:
  hooks:
    - go mod download
    - go generate ./...
#    - go vet -shadow ./...
    - go fmt ./...
    - yarn --cwd js build
    - go get github.com/GeertJohan/go.rice/rice
    - rice -i github.com/overmike/webterminal/cmd embed-go
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
